import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from '@/components/topbar';
import { Poppins } from "next/font/google";

const font = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${font.className} antialiased`}
      >
        <TopBar />
        {children}
      </body>
    </html>
  );
}
